name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true    
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64,amd64,arm
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Build CryFS image
      run: docker build . --file cryfs/Dockerfile --tag antaresinc/cryfs$SOURCE_COMMIT
