name: CryFs Build and Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug  
  release:
    types: [published]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true    
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64,amd64,arm
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        
    - name: Build CryFS image
      working-directory: ./cryfs
      run: docker build . --file Dockerfile --tag antaresinc/cryfs$SOURCE_COMMIT
